### ISSUE TITLE
Failed to create output directory ./cache/views

### ISSUE THREAD

**Issue by aavrug** [clthck/cakephp-jade#2] opened 2016-05-24 03:50 UTC
Done with step by step setup as guided but getting error when trying to reload the .ctp.jade file "**Failed to create output directory ./cache/views**"

**Comment by clthck** [comment] 2016-05-24 06:21
@aavrug I'll check the issue. thanks for reporting this.

**Comment by clthck** [comment] 2016-05-24 06:31
can you please check if `tmp` folder is writable in your project?

**Comment by aavrug** [comment] 2016-05-24 07:05
I have fixed and created a PR.

**Comment by clthck** [comment] 2016-05-24 07:55
I know but please confirm that your tmp folder is writable.

**Comment by aavrug** [comment] 2016-05-24 08:33
Yes I my application's tmp folder is having 777 permission.

**Comment by clthck** [comment] 2016-05-30 02:43
I'll review and update you soon.

**Comment by aavrug** [comment] 2016-05-31 03:53
Ok

**Comment by clthck** [comment] 2016-05-31 07:05
Merged the PR. Please try the latest commit in your app and let me know if the issue is fixed.

**Closed** 2016-07-04 08:12 UTC
